//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseDetails
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<decimal> PurchaseAmount { get; set; }
        public Nullable<decimal> SaleAmount { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Purchases Purchases { get; set; }
    }
}
