//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sales()
        {
            this.SaleDetails = new HashSet<SaleDetails>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string DocumentType { get; set; }
        public string DocumentNumber { get; set; }
        public string ClientDocument { get; set; }
        public string ClientName { get; set; }
        public Nullable<decimal> PayAmount { get; set; }
        public Nullable<decimal> ChangeAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleDetails> SaleDetails { get; set; }
        public virtual Users Users { get; set; }
    }
}
